### ISSUE TITLE
Does not work with ubuntu tomcat9 installation

### ISSUE THREAD

**Issue by jimkont** [zengkid/SmartTomcat#59]
I have installed tomcat 9 with the default ubuntu repositories and set the plugin configuration to `/usr/share/tomcat9/` which is identified correctly

![image](https://user-images.githubusercontent.com/1047581/95181987-afdab180-07cc-11eb-8f76-c8047b3a8e59.png)

when I try to run the project I initially get
`Error running 'run': /home/user/.SmartTomcat/ProjectName/com.xyz.abc/conf (Is a directory)`

I tried to delete the folder but it gets recreate every time.

When I converted `conf` to a file, I then get the error:

`Error running 'run': /usr/share/tomcat9/conf (No such file or directory)`

if I set tomcat to `/var/lib/tomcat9/` I get:
`Error running 'run': The Tomcat installation configured doesn't contains a bin folder`

Is this a bug or is it related to how ubuntu sets the tomcat folders (different folder for `bin` and `conf`)?

**Comment by zengkid** [comment]
@jimkont for ubuntu repositories  installation,  tomcat conf folder will install in /etc/tomcat9  instead of %tomcat_home%/conf.
the plugin will find %tomcat_home%/conf, but not found it.
the solution as below:
you can copy /etc/tomcat9 to %tomcat_home%/conf or
you can donwload tomcat9.zip instead of apt-get installation.

**Comment by jimkont** [comment]
thank you for the prompt support and the suggestion

I attempted to create symbolic links to resolve this but was getting permission issues. So, decided to use a separate tomacat zip and it works fine now
